[[plugins]]
repo = 'Shougo/denite.nvim'
on_event = 'BufRead'
hook_add = '''
nmap <Space> [denite]
nmap <silent> [denite]t :<C-u>Denite filetype<CR>
nmap <silent> [denite]p :<C-u>DeniteProjectDir file_rec<CR>
nmap <silent> [denite]f :<C-u>Denite file_rec<CR>
nmap <silent> [denite]l :<C-u>Denite line<CR>
nmap <silent> [denite]g :<C-u>Denite grep<CR>
nmap <silent> [denite]b :<C-u>Denite buffer<CR>
nmap <silent> [denite]] :<C-u>DeniteCursorWord grep<CR>
nmap <silent> [denite]r :<C-u>Denite -resume<CR>
nmap <silent> [denite]; :<C-u>Denite -resume -immediately -select=+1<CR>
nmap <silent> [denite]- :<C-u>Denite -resume -immediately -select=-1<CR>
nmap <silent> [denite]r :<C-u>Denite -resume -mode=normal<CR>
" nmap <silent> / :<C-u>Denite -auto-resize line<CR>
" nmap <silent> [denite]<C-d> :<C-u>call denite#start([{'name': 'file_rec', 'args': ['~/dotfiles']}])<CR>
" nmap <silent> <C-u>u :<C-u>Denite file_mru<CR>
" nmap <silent> <C-u>y :<C-u>Denite neoyank<CR>
'''
hook_post_source = '''
call denite#custom#source('file_rec', 'matchers', ['matcher_substring'])
if executable('rg')
  " call denite#custom#var('file_rec', 'command', ['rg', '--files', '--glob', '!.git', '!.svn', ''])
  call denite#custom#var('grep', 'command', ['rg'])
  call denite#custom#var('grep', 'default_opts', ['--vimgrep', '--no-heading'])
  call denite#custom#var('grep', 'recursive_opts', [])
  call denite#custom#var('grep', 'pattern_opt', ['--regexp'])
  call denite#custom#var('grep', 'separator', ['--'])
  call denite#custom#var('grep', 'final_opts', [])
elseif executable('ag')
  " call denite#custom#var('file_rec', 'command', ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
  " call denite#custom#var('grep', 'command', ['ag'])
  " call denite#custom#var('grep', 'default_opts', ['-i', '--vimgrep'])
  " call denite#custom#var('grep', 'recursive_opts', [])
  " call denite#custom#var('grep', 'pattern_opt', [])
  " call denite#custom#var('grep', 'separator', ['--'])
  " call denite#custom#var('grep', 'final_opts', [])
endif
'''
